In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [35]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [36]:
## Define the vocabulary size
voc_size=10000

In [37]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [38]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2978, 9161, 4227, 3263],
 [2978, 9161, 4227, 1353],
 [2978, 5330, 4227, 5373],
 [3088, 4130, 6139, 896, 6128],
 [3088, 4130, 6139, 896, 3008],
 [2311, 2978, 623, 4227, 9571],
 [9315, 7801, 2221, 896]]

In [24]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [39]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2978 9161 4227 3263]
 [   0    0    0    0 2978 9161 4227 1353]
 [   0    0    0    0 2978 5330 4227 5373]
 [   0    0    0 3088 4130 6139  896 6128]
 [   0    0    0 3088 4130 6139  896 3008]
 [   0    0    0 2311 2978  623 4227 9571]
 [   0    0    0    0 9315 7801 2221  896]]


In [40]:
## feature representation
dim=10

In [42]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [43]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[-0.04370049, -0.0252478 ,  0.0151406 ,  0.0052563 ,
         -0.04689969,  0.03065181, -0.00050483, -0.03030934,
          0.04249206, -0.04168166],
        [-0.01152039, -0.01553296, -0.03988264, -0.0402822 ,
          0.04387501,  0.0405383 , -0.04073511, -0.00260614,
         -0.01862937,  0.02875367],
        [-0.02369639, -0.04799727, -0.00531968, -0.01284232,
         -0.03964316, -0.04682254,  0.02835793,  0.02637834,
          0.046103  , -0.0045131 ],
        [-0.01238352, -0.01668018, -0.03916711, -0.04282406,
         -0.02738202,  0.00635352, -0.00782263,  0.01789744,
         -0.03261536,  0.04087713],
        [ 0.01247527,  0.00192151, -0.00517832,  0.04150934,
          0.00858226, -0.01963592,  0.04176498, -0.01504352,
          0.02756968,  0.0379537 ],
        [ 0.01247527,  0.00192151, -0.00517832,  0.04150934,
          0.00858226, -0.01963592,  0.04176498, -0.01504352,
          0.02756968,  0.0379537 ],
        [ 0.01247527,  0.00192151, -0.00517832,  0.0

In [44]:
embedded_docs[0]

array([   0,    0,    0,    0, 2978, 9161, 4227, 3263], dtype=int32)

In [32]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>